inherit_from: /usr/local/Homebrew/Library/.rubocop.yml

Sorbet/FalseSigil:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: percent

Lint/AmbiguousRegexpLiteral:
  Enabled: false
