name: CI
on:
  push:
    branches: [main]
    paths: '**.rb'
  pull_request:
    paths: '**.rb'
  schedule:
  - cron: 0 5 * * *

jobs:
  CI:
    runs-on: macos-latest
    steps:
    - name: ${{github.workflow}}
      uses: danielbayley/homebrew-pipeline@main
      env:
        ACTIONS_STEP_DEBUG: ${{secrets.ACTIONS_STEP_DEBUG}}
      with:
        skip-install: >-
          dracula-ableton-live,
          dracula-colorslurp,
          dracula-drafts,
          dracula-snippetslab
